### ISSUE TITLE
TypeError: _split_row() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by pree** [jgrassler/mkdocs-pandoc#22]
When I try to generate a .pd with `mkdocs2pandoc -f mkdocs.yml -o output.pd` in my docker image (schizopriest/mkdocs) on gitlab-ci, I get the following error:
```bash
Traceback (most recent call last):
  File "/usr/bin/mkdocs2pandoc", line 11, in <module>
    load_entry_point('mkdocs-pandoc==0.2.6', 'console_scripts', 'mkdocs2pandoc')()
  File "/usr/lib/python2.7/site-packages/mkdocs_pandoc/cli/mkdocs2pandoc.py", line 80, in main
    for line in pconv.convert():
  File "/usr/lib/python2.7/site-packages/mkdocs_pandoc/pandoc_converter.py", line 165, in convert
    lines = mkdocs_pandoc.filters.tables.TableFilter().run(lines)
  File "/usr/lib/python2.7/site-packages/mkdocs_pandoc/filters/tables.py", line 177, in run
    ret.extend(self.convert_table(block))
  File "/usr/lib/python2.7/site-packages/mkdocs_pandoc/filters/tables.py", line 91, in convert_table
    for i in range(0, len(self._split_row(lines_orig[0], has_border))):
TypeError: _split_row() takes exactly 2 arguments (3 given)
```

**Comment by nkaul** [comment]
I have the same error related to parsing of tables.

**Comment by immunochomik** [comment]
I have the same error it looks like Python-Markdown changed significantly underneath the mkdocs-pandoc

**Comment by immunochomik** [comment]
the problem is in the Marcdown 2.6.8 so if you install 2.6.7 it will work

**Comment by mrspaceman** [comment]
executing ' sudo pip install Markdown==2.6.7' fails with 

```
Collecting Markdown==2.6.7
  Could not find a version that satisfies the requirement Markdown==2.6.7 (from versions: )
No matching distribution found for Markdown==2.6.7
```

I'm on ubuntu 16.04.

any ideas how to fix this ?

**Comment by JGuillaumin** [comment]
You should use : pip install --upgrade markdown==2.6.7
