### ISSUE TITLE
pages -> nav

### ISSUE THREAD

**Issue by charlesreid1** [jgrassler/mkdocs-pandoc#29]
In `mkdocs.yml`, the `pages:` directive is being deprecated in favor of the `nav:` directive. This means that eventually `mkdocs-pandoc` will not work with functional `mkdocs.yml` files.

Here's the error you will see if you use `nav:` (as per mkdocs spec) instead of `pages:`:

```
$ mkdocs2pandoc > mydocs.pd
Traceback (most recent call last):
  File "/Users/charles/davis/dahak/dahak-comparison/vp/bin/mkdocs2pandoc", line 11, in <module>
    sys.exit(main())
  File "/Users/charles/davis/dahak/dahak-comparison/vp/lib/python3.6/site-packages/mkdocs_pandoc/cli/mkdocs2pandoc.py", line 80, in main
    for line in pconv.convert():
  File "/Users/charles/davis/dahak/dahak-comparison/vp/lib/python3.6/site-packages/mkdocs_pandoc/pandoc_converter.py", line 103, in convert
    pages = self.flatten_pages(self.config['pages'])
KeyError: 'pages'
```

**Comment by catcosmo** [comment]
fixed for mkdocs >1.0.4 in this pull-request:
https://github.com/jgrassler/mkdocs-pandoc/pull/30
